"""
DebateMoi — PDF Export
=======================
Generates a colorful, styled PDF transcript of the debate using fpdf2.
Color scheme: Cyan for Pro, Magenta for Con, Gold for Judge/Verdict.
"""

import io
import json
import re
from datetime import datetime, timezone
from fpdf import FPDF

def _clean_unicode(text: str) -> str:
    """Replace common unicode characters to prevent fpdf latin-1 encoding errors."""
    if not text:
        return ""
    replacements = {
        '’': "'", '‘': "'", '“': '"', '”': '"', '–': '-', '—': '-', '…': '...',
        '•': '-', '\u2022': '-', '\u2018': "'", '\u2019': "'", '\u201c': '"', '\u201d': '"',
        '\u2013': '-', '\u2014': '-', '\u2026': '...', '⚔️': '>', '🛡️': '<', '⚖️': '=',
        '📝': '', '🔑': '', '🏆': '', '❌': '', '✅': '', '🎭': ''
    }
    for search, replace in replacements.items():
        text = text.replace(search, replace)
    # Strip any remaining non-latin1 characters
    return text.encode('latin-1', 'ignore').decode('latin-1')

class DebatePDF(FPDF):
    """Custom PDF with DebateMoi branding."""

    def header(self):
        # Banner background
        self.set_fill_color(10, 10, 15)
        self.rect(0, 0, 210, 30, 'F')
        # Title
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(0, 212, 255)  # Cyan
        self.cell(0, 15, "D E B A T E M O I", align="C", new_x="LMARGIN", new_y="NEXT")
        
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(110, 110, 120)
        self.cell(0, 4, "MULTI-AGENT DEBATE TRANSCRIPT", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 100, 110)
        self.cell(0, 10, f"Generated by DebateMoi  |  Page {self.page_no()}", align="C")


def generate_debate_pdf(state: dict, session_id: str = "") -> bytes:
    """
    Generate a colorful PDF from the debate state.

    Args:
        state: The debate state dictionary with arguments and verdict.
        session_id: The session identifier.

    Returns:
        PDF as bytes, ready for st.download_button.
    """
    pdf = DebatePDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # -- Topic Section --
    pdf.set_fill_color(20, 20, 30)
    pdf.set_draw_color(0, 212, 255)
    pdf.set_line_width(0.5)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_text_color(255, 255, 255)
    
    topic_text = _clean_unicode(state.get('topic', 'N/A'))
    # Wrap topic in newlines to create natural vertical padding inside the cell
    topic_padded = f"\nTopic: {topic_text}\n"
    
    pdf.set_x(10)
    pdf.multi_cell(190, 8, topic_padded, border=1, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_line_width(0.2)
    pdf.ln(12)

    # -- Metadata --
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 130)
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    meta = f"Session: {session_id}  |  Rounds: {max(len(state.get('arguments_for', [])), len(state.get('arguments_against', [])))}  |  Generated: {timestamp}"
    pdf.cell(0, 6, meta, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # -- Debate Rounds --
    args_for = state.get("arguments_for", [])
    args_against = state.get("arguments_against", [])
    rounds_played = max(len(args_for), len(args_against))

    for i in range(rounds_played):
        # Round header
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_text_color(200, 200, 210)
        pdf.set_fill_color(30, 30, 45)
        pdf.cell(0, 10, f"  Round {i + 1}", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # Pro argument
        if i < len(args_for):
            _render_argument(pdf, "PRO", args_for[i]["content"],
                             border_color=(0, 212, 255), text_color=(0, 180, 220))

        # Con argument
        if i < len(args_against):
            _render_argument(pdf, "CON", args_against[i]["content"],
                             border_color=(255, 0, 110), text_color=(220, 0, 95))

        pdf.ln(5)

    # -- Verdict Section --
    _render_verdict(pdf, state)

    # Output to bytes
    return bytes(pdf.output())


def _render_argument(pdf: DebatePDF, label: str, content: str,
                     border_color: tuple, text_color: tuple):
    """Render a single argument block with colored border."""
    x_start = pdf.get_x()
    y_start = pdf.get_y()

    # Label
    icon = ">>>" if label == "PRO" else "<<<"
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*text_color)
    pdf.cell(0, 8, f"  {icon}  {label} AGENT", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 70)
    
    cleaned = _clean_unicode(content)
    for line in cleaned.split('\n'):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue
            
        pdf.set_x(15)
        if line.startswith('**') and '**:' in line:
            # Handle inline bold labels like "**Claim**: some text"
            title, rest = line.split('**:', 1)
            title = title.strip('* ')
            pdf.set_font("Helvetica", "B", 10)
            pdf.set_text_color(200, 200, 210)
            # We don't have inline bold in simple fpdf, so we print the title then the rest on a new line
            pdf.multi_cell(180, 5, title + ":", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 70)
            pdf.set_x(18)
            pdf.multi_cell(177, 5, rest.strip(), new_x="LMARGIN", new_y="NEXT")
        elif line.startswith('**') and line.endswith('**'):
            # Handle full-line headings
            pdf.ln(2)
            pdf.set_x(15)
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(*border_color)
            pdf.multi_cell(180, 6, line.strip('* '), new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(60, 60, 70)
        else:
            # Normal text
            line = line.replace('**', '') # Strip any remaining bold tags
            pdf.multi_cell(180, 5, line, new_x="LMARGIN", new_y="NEXT")

    y_end = pdf.get_y()

    # Left border accent line
    pdf.set_draw_color(*border_color)
    pdf.set_line_width(1.5)
    pdf.line(11, y_start, 11, y_end)
    pdf.set_line_width(0.2)

    pdf.ln(4)


def _render_verdict(pdf: DebatePDF, state: dict):
    """Render the verdict section with gold styling."""
    pdf.add_page()

    # Verdict banner
    pdf.set_fill_color(40, 35, 10)
    pdf.set_draw_color(255, 215, 0)
    y_start = pdf.get_y()
    pdf.rect(10, y_start, 190, 15, 'DF')
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(255, 215, 0)
    pdf.set_xy(10, y_start + 2)
    pdf.cell(190, 11, "JUDGE'S VERDICT", align="C")
    pdf.ln(20)

    winner = state.get("winner", "Unknown")
    reasoning = state.get("reasoning", "No reasoning available.")

    # Winner announcement
    pdf.set_font("Helvetica", "B", 18)
    winner_color = (0, 212, 255) if winner == "Pro" else (255, 0, 110)
    pdf.set_text_color(*winner_color)
    pdf.cell(0, 12, f"Winner: {winner.upper()} AGENT", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Reasoning
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(255, 215, 0)
    pdf.cell(0, 8, "Reasoning:", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(60, 60, 70)
    pdf.multi_cell(0, 5, _clean_unicode(reasoning), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Detailed scores
    judge_scores_str = state.get("judge_scores", "")
    if judge_scores_str:
        try:
            scores = json.loads(judge_scores_str)
            if not scores.get("parse_error"):
                _render_scores(pdf, scores)
        except (json.JSONDecodeError, ValueError):
            pass


def _render_scores(pdf: DebatePDF, scores: dict):
    """Render the detailed scoring table."""
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(200, 200, 210)
    pdf.cell(0, 10, "Detailed Scores", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)

    categories = ["logic", "evidence", "rhetoric", "rebuttal", "originality"]
    labels = ["Logical Consistency", "Evidence Strength", "Rhetorical Skill",
              "Rebuttal Quality", "Argument Originality"]

    pro_scores = scores.get("pro_scores", {})
    con_scores = scores.get("con_scores", {})

    # Table header
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_fill_color(30, 30, 45)
    pdf.set_text_color(200, 200, 210)
    pdf.cell(80, 8, "  Category", fill=True)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(45, 8, "PRO", align="C", fill=True)
    pdf.set_text_color(255, 0, 110)
    pdf.cell(45, 8, "CON", align="C", fill=True, new_x="LMARGIN", new_y="NEXT")

    # Table rows
    pdf.set_font("Helvetica", "", 10)
    for cat, label in zip(categories, labels):
        pdf.set_text_color(80, 80, 90)
        pdf.cell(80, 7, f"  {label}")
        pdf.set_text_color(0, 180, 220)
        pdf.cell(45, 7, str(pro_scores.get(cat, "-")), align="C")
        pdf.set_text_color(220, 0, 95)
        pdf.cell(45, 7, str(con_scores.get(cat, "-")), align="C", new_x="LMARGIN", new_y="NEXT")

    # Totals
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(25, 25, 35)
    pdf.set_text_color(200, 200, 210)
    pdf.cell(80, 8, "  TOTAL", fill=True)
    pdf.set_text_color(0, 212, 255)
    pdf.cell(45, 8, str(scores.get("pro_total", "-")), align="C", fill=True)
    pdf.set_text_color(255, 0, 110)
    pdf.cell(45, 8, str(scores.get("con_total", "-")), align="C", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Key moments
    key_moments = scores.get("key_moments", [])
    if key_moments:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(255, 215, 0)
        pdf.cell(0, 8, "Key Moments:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 70)
        for moment in key_moments:
            pdf.cell(5, 6, "")
            pdf.multi_cell(0, 5, f"  * {_clean_unicode(moment)}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

    # Deciding factor
    deciding = scores.get("deciding_factor", "")
    if deciding:
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(255, 215, 0)
        pdf.cell(0, 8, "Deciding Factor:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(80, 80, 90)
        pdf.multi_cell(0, 5, _clean_unicode(deciding), new_x="LMARGIN", new_y="NEXT")
